--
-- PostgreSQL database dump
--

\restrict efzLjbC6DrXMcBVIzGzSxwvY1hnzIdi7RT0ouHyuuRCAV1DiMawQssdMrITjzr0

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: market_data; Type: TABLE; Schema: public; Owner: mahii
--

CREATE TABLE public.market_data (
    id bigint NOT NULL,
    name character varying(255),
    price double precision
);


ALTER TABLE public.market_data OWNER TO mahii;

--
-- Name: market_data_id_seq; Type: SEQUENCE; Schema: public; Owner: mahii
--

ALTER TABLE public.market_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.market_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portfolio; Type: TABLE; Schema: public; Owner: mahii
--

CREATE TABLE public.portfolio (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    stock_symbol character varying(255),
    user_id bigint
);


ALTER TABLE public.portfolio OWNER TO mahii;

--
-- Name: portfolio_id_seq; Type: SEQUENCE; Schema: public; Owner: mahii
--

ALTER TABLE public.portfolio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: mahii
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    stock_symbol character varying(255),
    "timestamp" timestamp(6) without time zone,
    type character varying(255),
    user_id bigint
);


ALTER TABLE public.transactions OWNER TO mahii;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: mahii
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: mahii
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    role character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO mahii;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: mahii
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: market_data; Type: TABLE DATA; Schema: public; Owner: mahii
--

COPY public.market_data (id, name, price) FROM stdin;
\.


--
-- Data for Name: portfolio; Type: TABLE DATA; Schema: public; Owner: mahii
--

COPY public.portfolio (id, quantity, stock_symbol, user_id) FROM stdin;
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: mahii
--

COPY public.transactions (id, price, quantity, stock_symbol, "timestamp", type, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: mahii
--

COPY public.users (id, email, password, role, username) FROM stdin;
\.


--
-- Name: market_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahii
--

SELECT pg_catalog.setval('public.market_data_id_seq', 1, false);


--
-- Name: portfolio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahii
--

SELECT pg_catalog.setval('public.portfolio_id_seq', 1, false);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahii
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahii
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: market_data market_data_pkey; Type: CONSTRAINT; Schema: public; Owner: mahii
--

ALTER TABLE ONLY public.market_data
    ADD CONSTRAINT market_data_pkey PRIMARY KEY (id);


--
-- Name: portfolio portfolio_pkey; Type: CONSTRAINT; Schema: public; Owner: mahii
--

ALTER TABLE ONLY public.portfolio
    ADD CONSTRAINT portfolio_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: mahii
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: mahii
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict efzLjbC6DrXMcBVIzGzSxwvY1hnzIdi7RT0ouHyuuRCAV1DiMawQssdMrITjzr0

